#InspIRCd-Censor-Generator.tcl Created by AlphaTech
#Fill out this configuration to get started!

#Set this to "file" to load a file. Set this to "http" to load an HTTP document.
set type "http"

#Set this to the document or webpage to use.
set file "http://www.bannedwordlist.com/lists/swearWords.txt"

#Set this to what to replace the bad words with.
set replace "<CENSORED>"

#DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW!
#DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW!
#DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW! - DON'T EDIT BELOW!

if {[info exists type]=="0" || [info exists file]=="0" || [info exists replace]=="0"} {puts "Your configuration is missing some settings!"; exit} else {}
if {$type=="" || $file=="" || $replace==""} {puts "Your configuration is missing some settings!"; exit} else {}

if {$type=="http"} {
package require http
if {[string match http://* "$file"]=="0"} {puts "Your HTTP page URL doesn't seem like a URL or it uses HTTPS which isn't supported!"; exit} else {}
set token [::http::geturl $file]
set data [::http::data $token]
} elseif {$type=="file"} {
set fp [open $file "r"]
set lines [read -nonewline $fp]
set data [split $lines "\n"]
}

puts "#Censor.conf for InspIRCd"
puts "#This file was generated by InspIRCd Censor Generator by AlphaTech"
puts "#Check out https://github.com/AlphaT3ch/InspIRCd-Censor-Generator-Tcl for more information"
puts ""
foreach line $data {
puts "<badword text=\"$line\" replace=\"$replace\">"
}

if {$type=="http"} {
::http::cleanup $token
} elseif {$type=="file"} {
close $fp
} else {}
